### PR TITLE
Added Ridge and Violin Plot (Raw and Normalised)

### PR DESCRIPTION
**Pull request by mariusrueve**
Every requested plot is implemented and should be fully working (render and download).

Also somer minor fixes and changes

### CODE REVIEW

**Comment by colindaven** [comment]
It seems to run fine, I recreated a container for it at the usual place. Please have a look since I'm off on holiday soon and need complete other tasks.

**Review by colindaven — APPROVED** [review]

**Comment by colindaven** [comment]
Following errors are occurring during (your? or Torstens ? ) testing


[[1]]

[[1]]

[[1]]

[[1]]

[[1]]

[[1]]

Warning: Error in strsplit: object 'ii' not found
  [No stack trace available]
[[1]]

[[1]]

[[1]]

[[1]]

[[1]]

[[1]]

Warning: Error in strsplit: object 'ii' not found
  [No stack trace available]

**Comment by mariusrueve** [comment]
Probably my testing. Currently I have errors in RStudio aswell and I don't know why, because everything was working yesterday. Trying to fix it

**Comment by mariusrueve** [comment]
`Warning: Error in strsplit: object 'ii' not found` --> fixed: typo got transferred through copy & paste.

`Warning: Error in readRDS: error reading from connection`
Reading the RDS file seems to have problems even though I didn't change the code

**Comment by mariusrueve** [comment]
Errors should be fixed https://github.com/MHH-RCUG/scrnaseq_app/pull/9/commits/07109ee5247c8fc2926857ab65f7aedd2823b261

**Pull request closed without merging**
